### ISSUE TITLE
Albums missing from albumlist.json files

### ISSUE THREAD

**Issue by dperron-ss** [RandomNinjaAtk/docker-lidarr-lad#31]
When searching Deezer for albums via the website, they readily display under the artist ID that LAD is looking for, but do not appear in the cached json files.

For instance, when looking for the sanitized album "consign-to-oblivion", which appears as ID #11774752 in Deezer under artist ID #1343, the attached json file is generated without that album.
[1343-albumlist.json.txt](https://github.com/RandomNinjaAtk/docker-lidarr-lad/files/4602826/1343-albumlist.json.txt)

**Comment by dperron-ss** [comment]
Strangely, The Quantum Enigma is also unable to match despite appearing in the json file, with matching track counts, sanitized album name, and artist ID.

**Comment by RandomNinjaAtk** [comment]
So after quick review, it appears that Musicbrainz doesn't have a release that matches the trackcount. And that is why its not matching.

See link:
https://musicbrainz.org/release-group/2fdb33fc-921d-4408-b0f0-da2a0f2f9952

You need to add the release to musicbrainz that matches more closely. Once it is added and imported into Lidarr, it should match....

I recommend using this tool to help accomplish that:
https://github.com/murdos/musicbrainz-userscripts#deezer_importer

This script is very dependent on Album Name, release year and track counts in order to find a match. So in this case, Mbrainz doesn't have a similar enough version. I hope that helps clear up the confusion... Doesn't look like there is anything that needs to be fixed, other then better matching records being added to Mbrainz...

**Comment by dperron-ss** [comment]
I'll take a look at Deezer Importer, it might help solve edge-cases in future.

Without undermining the obviously onerous amount of work it took to bodge all these services together in some semblance of sanity, I do find it frustratingly difficult to debug this project for my specific needs.

I have over a Petabyte of storage available for my music, I honestly don't care if the track count is too high. And let's be honest, Lidarr always picks the stupidest releases, so trusting it even a little bit isn't tenable: 2x 12" Vinyl default for a digital collection, really!?

Would you consider working out a configurable scale for specificity? I do understand that Deezer's library linking is hot garbage, with some albums not appearing under the band that owns them. All I really want is for the most likely album with the most tracks to be downloaded then compared against the artist's albums in musicbrainz.

**Comment by RandomNinjaAtk** [comment]
So 2 things, what your asking for I have no idea on how to implement, probably beyond my skillset... Also even if it were downloaded, Lidarr would likely never import them for the same reason. So it wouldn't actually help...

**Comment by dperron-ss** [comment]
Hmm, I guess I'll just have to find something that doesn't rely on Lidarr and it's buggy behaviour.

Thanks for the attention regardless.

**Comment by RandomNinjaAtk** [comment]
> Hmm, I guess I'll just have to find something that doesn't rely on Lidarr and it's buggy behaviour.
> 
> Thanks for the attention regardless.

Just FYI, I added a new DL mode, called "archive". This mode will get everything available. However, it does not use matching at all and may create duplicates if you didn't start with a clean library. I recommend using mode for new installs....
