### ISSUE TITLE
Various Artists

### ISSUE THREAD

**Issue by robflate** [RandomNinjaAtk/docker-lidarr-lad#37]
LAD MBZDB CACHE is taking about 1h30m to scan the entirety of MusicBrainz 'Various Artists' each time the cron is run. Is that normal? Various Artists is 1975 pages according to the logs. MBZDB CACHE finishes and seems to immediately start again. This results in my CPU being under load constantly.

I'm wondering what my best course of action is?
- Use a local MusicBrainz mirror?
- Delete 'Various Artists' from Lidarr?
- Something else?

Things I've tried;
- Set Metadata Profile to None.

A few more questions;
- Does LAD cache all Artists, regardless of if they are monitored or not?
- What exactly is happening when the MBZDB CACHE runs? Does it still have to check each artist and pages on subsequent runs?
- What happens if the script takes longer than 15 minutes to run? Does the next cron run just get skipped?

Some info about my setup;

DLMODE: "Audio"
AMODE: "wanted"
TRACKUPGRADE: "false"
VerifyTrackCount: "true"
amount: 1000000000
quality: "FLAC"
TagWithBeets: "true"
DownLoadArtistArtwork: "true"

--- And thanks for the amazing work on LAD!

**Comment by RandomNinjaAtk** [comment]
Local mirror does greatly speed things up, because you can increase it from 1 api query to 10 per second. I really haven't tested or used various artists since all the changes. 

So to answer your questions:
Does LAD cache all Artists, regardless of if they are monitored or not? Yes
What exactly is happening when the MBZDB CACHE runs? Does it still have to check each artist and pages on subsequent runs? 

MBZDB cache actually is only really used in the script at this point for Music Videos, if I recall. It does cache sort of intelligently by that it checks if the local cache is current and will only update it if changes are detected. So yes it runs every time, but shouldn't need to update frequently.

What happens if the script takes longer than 15 minutes to run? Does the next cron run just get skipped?
The script will not run more then one instance at a time. Unless you do something specifically to cause it to do so. So yes, it is effectively skipped.

**Comment by robflate** [comment]
Thanks for the answers. I'll have a look at a local MusicBrainz installation to see if I can speed things up.
