### ISSUE TITLE
Could not find a match

### ISSUE THREAD

**Issue by robflate** [RandomNinjaAtk/docker-lidarr-lad#38]
LAD downloaded a handful of albums when I first installed it but now everything appears to go to `notfound.log`.

As an example, for the EP `Control` by `Disclosure`, both the MusicBrainz and Deezer pages show the album I want and it has the same track count and release year on both;

`Disclosure :: Control (ID: 2065972a-160f-4348-9ba4-e1eb0cee818c) :: Could not find a match on "https://www.deezer.com/artist/409796" using Release or Record Name, Track Count and Release Year, check artist page for album, ep or single. If exists, update musicbrainz db with matching album name, track count, year to resolve the error`

MusicBrainz: https://musicbrainz.org/release-group/2065972a-160f-4348-9ba4-e1eb0cee818c
Deezer: https://www.deezer.com/artist/409796

As another example, for the EP `LP1` by `FKA twigs`, both the MusicBrainz and Deezer pages show the album I want and it has the same track count and release year on both;

`FKA twigs :: LP1 (ID: c390b47b-71c0-461d-b563-e5344b4f84e5) :: Could not find a match on "https://www.deezer.com/artist/5039338" using Release or Record Name, Track Count and Release Year, check artist page for album, ep or single. If exists, update musicbrainz db with matching album name, track count, year to resolve the error`

MusicBrainz: https://musicbrainz.org/release-group/c390b47b-71c0-461d-b563-e5344b4f84e5
Deezer: https://www.deezer.com/en/artist/5039338

Any advice appreciated. Thanks.

**Comment by RandomNinjaAtk** [comment]
I'll need to look into it, not sure. I've mostly been using archive mode which doesn't require matching at all... Personally I recommend using archive mode...

**Comment by RandomNinjaAtk** [comment]
Give this a try instead: https://github.com/RandomNinjaAtk/docker-amd

**Comment by robflate** [comment]
Thanks. So I understand;

- [Docker-amd](https://hub.docker.com/r/linuxserver/lidarr) is a companion script and also requires a separate Lidarr container?
- Can any Lidarr image be used, i.e. [linuxserver](https://hub.docker.com/r/linuxserver/lidarr)?
- What settings are required in the Lidarr container...do I need to use the [Lidarr Configuration Recommendations](https://github.com/RandomNinjaAtk/docker-lidarr-lad#lidarr-configuration-recommendations) like with Lidarr-LAD?
- Does this replace [Lidarr-LAD](https://github.com/RandomNinjaAtk/docker-lidarr-lad)
- [Docker-amd](https://hub.docker.com/r/linuxserver/lidarr) has no GUI and no ports exposed?
- When [Docker-amd](https://hub.docker.com/r/linuxserver/lidarr) connects to the Lidarr API how does it send the API key? Is it sent in the headers as an `apikey` query or as `X-Api-Key`?
- The `DOWNLOADS` env variable says, `lidarr needs access to this directory`. Is there a specific volume name like `/downloads` to use with Lidarr and does this need entering anywhere in the Lidarr GUI?

Sorry for all the questions and thanks for all your hard work!

**Comment by RandomNinjaAtk** [comment]
Docker-amd is a companion script container and also requires a separate Lidarr container?
- Yes

Can any Lidarr image be used, i.e. linuxserver? 
- Yes, also if your using lidarr-lad, you can directly transition to Linuxserver.io container using the "preview" tag because that is the underlying image used for this container. All you would do to cleanup the existing config folder is to delete, the scripts directory because it is not used in the base image

What settings are required in the Lidarr container...do I need to use the Lidarr Configuration Recommendations like with Lidarr-LAD?
- No settings are really required, and you can still use the configuration recommendations as far as naming an import extras

Does this replace Lidarr-LAD
- Yes

Docker-amd has no GUI and no ports exposed?
- Correct, its a completely CLI based script, just like the one inside LAD, so no ports or gui is included

When Docker-amd connects to the Lidarr API how does it send the API key? Is it sent in the headers as an apikey query or as X-Api-Key?
- You add your lidarr url and api key to the docker config, it uses that to send notifications using curl

The DOWNLOADS env variable says, lidarr needs access to this directory. Is there a specific volume name like /downloads to use with Lidarr and does this need entering anywhere in the Lidarr GUI?
- This works similar to any other download client you may be using in another container. You need to make sure you have a volume that matches Lidarr's docker configuration and configure the variable to match the location. Because Lidarr will be notified of the download files and you need to make sure it has access to them. It's not possible to use remote path mapping like other download clients.

**Comment by RandomNinjaAtk** [comment]
Hope that answers your questions, for moving forward, open issues that pertain to the new docker script on its repo: https://github.com/RandomNinjaAtk/docker-amd
